# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifyApp
  pod 'SDWebImage'
  pod 'JGProgressHUD'
  pod 'Alamofire'
  pod 'ImageSlideshow'
  pod 'ImageSlideshow/Alamofire'
  
end
